# Tutorial to use with: https://github.com/andry81-devops/github-accum-stats
#

name: accum-gh-stats
description: 'GitHub composite action to request and accumulate a repository clones and/or views statistic'

inputs:
  deps_repo_owner:
    description: 'Owner of a repository used to checkout dependencies'
    required: true

  deps_repo_branch:
    description: 'Repository branch used to checkout dependencies'
    default: master

  deps_repo_read_token:
    description: 'PAT token to a repository used to checkout dependencies'
    default: ${{ github.token }}

  stat_repo_owner:
    description: 'Owner of a repository used to request the statistic'
    required: true

  stat_repo:
    description: 'Repository name used to request the statistic'
    required: true

  stat_entity:
    description: 'Statistic entity to request'
    required: true
    # variants:
    # - clones
    # - views

  commit_msg_entity:
    description: 'Commit message entity. The `stat_entity` does use if not defined.'
    # examples:
    # - cl
    # - vi

  stat_repo_read_token:
    description: 'PAT token to a repository used to request the statistic with statistic read access rights'
    required: true

  curl_flags:
    description: 'additional curl flags'
    # example:
    #   `-H 'Cache-Control: no-cache'`

  output_repo_owner:
    description: 'Owner of a repository used to output the statistic'
    required: true

  output_repo:
    description: 'Repository name used to output the statistic'
    required: true

  output_repo_branch:
    description: 'Repository branch used to output the statistic'
    default: master

  output_repo_dir:
    description: 'Output repository relative directory path to store requested and accumulated statistic'
    required: true
    # examples:
    # - traffic/clones
    # - traffic/views

  output_repo_write_token:
    description: 'PAT token to the output repository with write/push access rights'
    required: true

  env:
    description: environment variables
    # See dependent repositories and scripts for details.
    # examples:
    #   CONTINUE_ON_INVALID_INPUT=1
    #   CONTINUE_ON_EMPTY_CHANGES=1
    #   CONTINUE_ON_RESIDUAL_CHANGES=1
    #   ENABLE_GENERATE_CHANGELOG_FILE=1
    #   ENABLE_COMMIT_MESSAGE_DATE_WITH_TIME=1                            # insert the time string in format `HH:MMZ` additionally after the date in each commit message
    #   ENABLE_COMMIT_MESSAGE_DATE_TIME_WITH_LAST_CHANGED_DATE_OFFSET=1   # insert datetime suffix as offset to the last changed date in format `-DDT` to note the closest changed date
    #   CHANGELOG_FILE=changelog.txt

runs:
  using: "composite"
  steps:
    # step is required to workaround variable expansion in variables
    - name: declare dependent variables
      shell: bash
      run: |
        echo "GH_WORKFLOW_ROOT=$GITHUB_WORKSPACE/gh-workflow" >> $GITHUB_ENV

    - name: checkout gh-workflow@${{ inputs.deps_repo_branch }}
      uses: andry81-devops/gh-action--git-checkout@master
      with:
        repository: ${{ inputs.deps_repo_owner }}/gh-workflow
        ref:        ${{ inputs.deps_repo_branch }}
        path:       gh-workflow
        token:      ${{ inputs.deps_repo_read_token }}

        mkdir-p: >-
          ${{ env.GH_WORKFLOW_ROOT }}

    - name: update permissions
      shell: bash
      run: |
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/eval-from-args.sh
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/print-notice.sh
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/flush-print-annotations.sh
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/accum-stats.sh

    # step is required to pass environment variables externally
    - name: declare variables from lists
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          ${{ inputs.env }}

    - name: variables validation
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "CHANGELOG_FILE=${CHANGELOG_FILE:-"changelog.txt"}"

    - name: declare local variables
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "CHANGELOG_FILE=$GITHUB_WORKSPACE/gh-stats/${{ inputs.output_repo_dir }}/$CHANGELOG_FILE" \
          "stat_entity=${{ inputs.stat_entity }}" \
          "commit_msg_entity=${{ inputs.commit_msg_entity }}" \
          "stats_dir=$GITHUB_WORKSPACE/gh-stats/${{ inputs.output_repo_dir }}" \
          "stats_json=$GITHUB_WORKSPACE/gh-stats/${{ inputs.output_repo_dir }}/latest.json"

    - name: variables validation
      shell: bash
      run: |
        case "$stat_entity" in
          "views")  $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh "stat_entity_path=traffic/views";;
          "clones") $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh "stat_entity_path=traffic/clones";;
          *) $GH_WORKFLOW_ROOT/bash/github/print-error.sh "\`stat_entity\` input parameter is invalid: \`$stat_entity\`"; exit 255;;
        esac

    - name: declare local variables
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "changelog_dir=${CHANGELOG_FILE%/*}"

    - name: allocate directories
      shell: bash
      run: |
        # for details: https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "TEMP_DIR=${{ runner.temp }}/accum-stats"
        $GH_WORKFLOW_ROOT/bash/github/eval-from-args.sh -Ep \
          'mkdir -p "$TEMP_DIR"'

    - name: head annotations
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/print-notice.sh \
          "stat repo: https://github.com/${{ inputs.stat_repo_owner }}/${{ inputs.stat_repo }}" \
          "output repo dir: https://github.com/${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}/tree/${{ inputs.output_repo_branch }}/${{ inputs.output_repo_dir }}"

    - name: checkout gh-stats@${{ inputs.output_repo_branch }}
      uses: andry81-devops/gh-action--git-checkout@master
      with:
        repository: ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        ref:        ${{ inputs.output_repo_branch }}
        path:       gh-stats
        token:      ${{ inputs.output_repo_write_token }}

        mkdir-p: >-
          ${{ inputs.output_repo_dir }}
          ${{ env.changelog_dir }}

    - name: 'request `${{ inputs.stat_entity }}` json'
      shell: bash
      run: |
        # CAUTION:
        #   The `sed` has to be used to ignore blank lines by replacing `CR` by `LF`.
        #   This is required for uniform parse the curl output in both verbose or non verbose mode.
        #
        curl \
          --user "${{ inputs.stat_repo_owner }}:${{ inputs.stat_repo_read_token }}" \
          ${{ inputs.curl_flags }} \
          -H "Accept: application/vnd.github.v3+json" \
          -o "$stats_json" \
          "https://api.github.com/repos/${{ inputs.stat_repo_owner }}/${{ inputs.stat_repo }}/$stat_entity_path" \
          2>&1 | tee "$TEMP_DIR/curl-stderr.txt" | sed -E 's/\r([^\n])/\n\1/g' | grep -P '^(?:  [% ] |(?:  |  \d|\d\d)\d |[<>] )'
        last_error=$?
        echo $'---\n'"$(<"$stats_json")"$'\n---'
        if (( last_error )); then
          if [[ -s "$TEMP_DIR/curl-stderr.txt" ]]; then
            echo "$(<"$TEMP_DIR/curl-stderr.txt")"$'\n---'
          fi
        else
          if [[ ! -s "$stats_json" && -s "$TEMP_DIR/curl-stderr.txt" ]]; then
            echo "$(<"$TEMP_DIR/curl-stderr.txt")"$'\n---'
          fi
        fi

    - name: 'accumulate `${{ inputs.stat_entity }}`'
      id: accum-stats
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/accum-stats.sh
        # caution: no operation after that line if non zero exit code happens above

    - name: commit gh-stats
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/gh-stats
        git add .
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git commit -m "A/U: $COMMIT_MESSAGE_DATE_TIME_PREFIX: ${COMMIT_MESSAGE_PREFIX}${COMMIT_MESSAGE_SUFFIX:+" | "}$COMMIT_MESSAGE_SUFFIX"
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "HEAD_COMMIT_HASH=$(git rev-parse HEAD)"

    - name: push gh-stats
      uses: ad-m/github-push-action@master
      with:
        repository:   ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        branch:       ${{ inputs.output_repo_branch }}
        directory:    gh-stats
        github_token: ${{ inputs.output_repo_write_token }}

    - name: print commit parameters
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/print-notice.sh \
          "commit reference url: https://github.com/${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}/commit/$HEAD_COMMIT_HASH"

    - name: flush print annotations
      if: always()
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/flush-print-annotations.sh
